ALURAFLIX

<html lang="pt-BR">



<head>

    <link rel="stylesheet" href="styles.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link

        href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"

        rel="stylesheet">

    <title>AdriFlix</title>

</head>



<body>

    <header>AdriFLIX

    </header>



    <section class="chamada">

        <div class="chamada-texto">

            <h1>ATRAVÉS DO ARANHAVERSO</h1>

            <p>#homem-aranha</p>

        </div>



        <div>

            <iframe width="560" height="315" src="https://www.youtube.com/embed/gt_fAE1Eg2Q?si=EEv-tsY_b1B2OwKE"

                title="YouTube video player" frameborder="0"

                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"

                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

        </div>

    </section>



    <section class="categoria">

        <h2>Filmes e séries</h2>

        <div class="categoria-videos">

            <a href="https://www.youtube.com/watch?v=cs15QqG6Gjc">

                <img src="https://img.youtube.com/vi/cs15QqG6Gjc/maxresdefault.jpg" />

            </a>

            <a href="https://www.youtube.com/watch?v=nCmIwcycUJ8">

                <img src="https://img.youtube.com/vi/nCmIwcycUJ8/maxresdefault.jpg" />

            </a>

            <a href="https://www.youtube.com/watch?v=FvRmEapoHRc">

                <img src="https://img.youtube.com/vi/FvRmEapoHRc/maxresdefault.jpg" />

            </a>

            <a href="https://www.youtube.com/watch?v=Ipkw_hWW-Hw">

                <img src="https://img.youtube.com/vi/Ipkw_hWW-Hw/maxresdefault.jpg" />

            </a>

            <a href="https://www.youtube.com/watch?v=d4DzMNGoyis">

                <img src="https://img.youtube.com/vi/d4DzMNGoyis/maxresdefault.jpg" />

            </a>

        </div>

    </section>



</body>



</html># Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
